version: "3.3"
volumes:
  php-fpm-socket:
  db-store:
services:
  app_dir:
    # image: php:7-fpm
    build: ./infra/docker/php
    volumes:
      - ./app_dir:/work/app_dir

  admin_dir:
    build: ./infra/docker/php
    volumes:
      - ./admin_dir:/work/admin_dir

  api_dir:
    build: ./infra/docker/php
    volumes:
      - ./api_dir:/work/api_dir

  web_server:
    build: ./infra/docker/nginx
    ports:
      - 8021:80
      - 8022:81
      - 8023:82
    depends_on:
      - app_dir
      - admin_dir
      - api_dir
    volumes:
      # - php-fpm-socket:/var/run/php-fpm
      - ./app_dir:/work/app_dir
      - ./admin_dir:/work/admin_dir
      - ./api_dir:/work/api_dir
      - ./infra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    build: ./infra/docker/mysql
    ports:
      - 3309:3306
    volumes:
      - db-store:/var/lib/mysql

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

